/* This file is generated by scripts/generate-i18n-resources.mjs. Do not edit by hand. */

export const enUSResources = {
  "common": {
    "languages": {
      "zhCN": "中文",
      "enUS": "EN"
    },
    "states": {
      "selected": "Selected",
      "imported": "Imported",
      "importable": "Importable",
      "sample": "Sample",
      "loading": "Loading",
      "ready": "Live",
      "fallback": "Local fallback",
      "error": "Error"
    }
  },
  "site": {
    "header": {
      "ariaLabel": "Soul site header",
      "navAriaLabel": "Soul site navigation",
      "brandBadge": "Agent Soul Editor",
      "description": "HagiSoul gives developers a faster workspace for creating, sharing, and browsing Souls.",
      "themeButton": "Theme",
      "themeToDark": "Switch to dark theme",
      "themeToLight": "Switch to light theme",
      "languageSwitcherAria": "Interface language switcher"
    },
    "footer": {
      "ariaLabel": "HagiSoul footer",
      "brandSectionAria": "Brand overview",
      "tagline": "Define your Agent’s soul, fast.",
      "description": "HagiSoul focuses on developer workflows with a faster experience for creating, sharing, and browsing Souls.",
      "copyright": "© {{year}} HagiCode. All rights reserved.",
      "sections": {
        "related": "Related links",
        "community": "Community and support"
      }
    },
    "links": {
      "docs": {
        "label": "Docs",
        "ariaLabel": "Open the HagiCode docs site"
      },
      "website": {
        "label": "Website",
        "ariaLabel": "Open the HagiCode website"
      },
      "trait": {
        "label": "Trait",
        "ariaLabel": "Open the HagiTrait builder"
      },
      "github": {
        "label": "GitHub",
        "ariaLabel": "Open the HagiCode GitHub repository"
      },
      "discord": {
        "label": "Discord",
        "ariaLabel": "Open the HagiCode Discord community"
      },
      "qqGroup": {
        "label": "QQ Group 610394020",
        "ariaLabel": "Open the HagiCode QQ group 610394020"
      },
      "email": {
        "label": "support@hagicode.com",
        "ariaLabel": "Email the HagiCode support team"
      },
      "steam": {
        "label": "Steam",
        "ariaLabel": "Open the official HagiCode Steam store page"
      },
      "filings": {
        "icpAriaLabel": "View the ICP filing record",
        "publicSecurityAriaLabel": "View the public security filing record"
      }
    }
  },
  "home": {
    "workbenchAriaLabel": "Soul Builder workbench",
    "hero": {
      "eyebrow": "Soul Builder",
      "title": "Compose the persona frame before the output starts drifting.",
      "description": "Pick a base role, lock an expression rule, and polish the live prompt inside one monochrome workbench.",
      "primaryAction": "Jump to editor",
      "secondaryAction": "Open docs",
      "stats": {
        "catalog": "Base roles",
        "expression": "Expression rules",
        "state": "Workbench"
      },
      "state": {
        "ready": "Ready to copy",
        "draft": "Needs composition"
      }
    },
    "slotRail": {
      "leftAriaLabel": "Left homepage slots",
      "rightAriaLabel": "Right homepage slots",
      "inputsEyebrow": "builder inputs",
      "contextEyebrow": "builder context",
      "recommended": "recommended"
    },
    "slots": {
      "catalog": {
        "label": "Base role",
        "title": "Choose a base role",
        "description": "Lock in the base role first to define the persona frame and core boundaries.",
        "emptyState": "No base roles are available right now."
      },
      "expression": {
        "label": "Expression",
        "title": "Choose an expression style",
        "description": "Then add expression rules to tighten cadence, tone, and output rhythm.",
        "emptyState": "No expression rules are available right now."
      }
    },
    "drawer": {
      "inputBadge": "Input drawer",
      "contextBadge": "Context drawer",
      "defaultTitle": "Context drawer",
      "defaultDescription": "No guidance is available for this slot yet.",
      "defaultEmptyState": "There is no content for this slot yet.",
      "closeLabel": "Close drawer"
    }
  },
  "builder": {
    "categories": {
      "all": "All",
      "healingCompanion": "Healing and companionship",
      "characterPersona": "Character personas",
      "professionalIdentity": "Professional identities",
      "communityCulture": "Community cultures",
      "contrastAndScene": "Contrast and scene-specific"
    },
    "materialLibrary": {
      "searchAriaLabel": "Search materials",
      "mainCategoryLabel": "Base role categories",
      "refreshInspiration": "Refresh inspiration",
      "selectedBadge": "Selected",
      "importedBadge": "Imported",
      "importableBadge": "Importable",
      "styleFallback": "Sample",
      "clickToImport": "Click to import",
      "emptyFiltered": "No materials match the current filters.",
      "emptyInspiration": "Official inspiration cards are unavailable right now. You can still build with local base roles and expression rules.",
      "panels": {
        "main": {
          "badge": "Base role",
          "title": "Pick a base role first.",
          "placeholder": "Search base roles"
        },
        "rules": {
          "badge": "Expression",
          "title": "Then lock the expression style.",
          "placeholder": "Search expression rules"
        },
        "inspiration": {
          "badge": "Inspiration",
          "title": "Import an official inspiration card.",
          "placeholder": "Search inspiration cards"
        },
        "all": {
          "badge": "Material library",
          "title": "Start with reusable fragments.",
          "placeholder": "Search base roles, rules, or inspiration cards"
        }
      },
      "sections": {
        "mainTitle": "Base roles",
        "mainEyebrow": "who",
        "rulesTitle": "Expression rules",
        "rulesEyebrow": "how",
        "inspirationTitle": "Official inspiration cards",
        "inspirationEyebrow": "inspiration",
        "remoteSourceTitle": "Official inspiration source"
      },
      "remote": {
        "loadingInitial": "Loading official inspiration cards.",
        "loadingRefresh": "Refreshing official inspiration cards.",
        "fallback": "The official inspiration source is offline, so local sample cards are shown.",
        "empty": "The official inspiration source is empty, so the view has switched back to local sample cards.",
        "ready": "Official inspiration cards are available.",
        "errorWithFallback": "{{detail}} Switched back to local sample cards.",
        "state": {
          "idle": "Idle",
          "loading": "Loading",
          "ready": "Live",
          "fallback": "Fallback",
          "error": "Error"
        }
      }
    },
    "preview": {
      "panelTitle": "Agent Soul Editor",
      "defaultTitle": "Soul Builder Preview",
      "untitledSoul": "Untitled Soul",
      "feedbackSummary": "{{filled}} of 3 slots are filled. The preview recalculates live in order.",
      "fallbackPartial": "Finish the remaining slots and the complete preview will refresh here automatically.",
      "fallbackInitial": "Fill the base role and expression slots first before the preview can form a complete result.",
      "nextReady": "All three slots are merged. Keep polishing the text or copy the current preview right away.",
      "nextIncomplete": "Complete the missing slots before the preview can settle.",
      "previewEyebrow": "preview",
      "previewReady": "Merged and ready to copy",
      "previewIncomplete": "Required slots are missing",
      "copyButton": "Copy preview",
      "currentCompositionTitle": "Current composition",
      "nextStepTitle": "Next step",
      "currentCompositionMain": "Base role: {{value}}",
      "currentCompositionRule": "Expression: {{value}}",
      "currentCompositionCustom": "Custom text: {{value}}",
      "slots": {
        "main": {
          "eyebrow": "slot 01 · base role",
          "title": "Base role slot",
          "placeholder": "Choose a base role card on the left, then keep editing if needed.",
          "ariaLabel": "Base role slot",
          "emptySummary": "Base role not filled"
        },
        "rule": {
          "eyebrow": "slot 02 · expression",
          "title": "Expression slot",
          "placeholder": "Choose an expression card on the left, then keep editing if needed.",
          "ariaLabel": "Expression slot",
          "emptySummary": "Expression not filled"
        },
        "custom": {
          "eyebrow": "slot 03 · custom",
          "title": "Custom text slot",
          "placeholder": "Add your own limits, preferences, catchphrases, or extra requirements.",
          "ariaLabel": "Custom text slot",
          "filledSummary": "{{count}} characters added",
          "emptySummary": "No extra requirements yet"
        }
      },
      "hints": {
        "missingBoth": "Fill the base role and expression slots first before generating a complete result.",
        "missingMain": "Fill the base role slot first.",
        "missingRule": "Fill the expression slot first.",
        "copyIncompleteFallback": "The core composition is not ready yet.",
        "copySuccess": "The preview text has been copied.",
        "inspirationImported": "Imported the inspiration card \"{{title}}\"."
      }
    }
  }
} as const
