/* This file is generated by scripts/generate-i18n-resources.mjs. Do not edit by hand. */

export const frFRResources = {
  "common": {
    "languages": {
      "zhCN": "中文",
      "enUS": "EN"
    },
    "states": {
      "selected": "Sélectionné",
      "imported": "Importé",
      "importable": "Importable",
      "sample": "Exemple",
      "loading": "Chargement",
      "ready": "En ligne",
      "fallback": "Repli local",
      "error": "Erreur"
    }
  },
  "site": {
    "header": {
      "ariaLabel": "En-tête du site Soul",
      "navAriaLabel": "Navigation du site Soul",
      "brandBadge": "Éditeur Agent Soul",
      "description": "HagiSoul offre aux développeurs un espace plus rapide pour créer, partager et parcourir des Souls.",
      "themeButton": "Thème",
      "themeToDark": "Passer au thème sombre",
      "themeToLight": "Passer au thème clair",
      "languageSwitcherAria": "Changer la langue de l’interface"
    },
    "footer": {
      "ariaLabel": "Pied de page HagiSoul",
      "brandSectionAria": "Présentation de la marque",
      "tagline": "Définis vite l’âme de ton Agent.",
      "description": "HagiSoul se concentre sur les workflows développeur et offre une expérience plus rapide pour créer, partager et parcourir des Souls.",
      "copyright": "© {{year}} HagiCode. Tous droits réservés.",
      "sections": {
        "related": "Liens associés",
        "community": "Communauté et support"
      }
    },
    "links": {
      "docs": {
        "label": "Docs",
        "ariaLabel": "Ouvrir le site de documentation HagiCode"
      },
      "website": {
        "label": "Site web",
        "ariaLabel": "Ouvrir le site HagiCode"
      },
      "trait": {
        "label": "Trait",
        "ariaLabel": "Ouvrir le builder HagiTrait"
      },
      "github": {
        "label": "GitHub",
        "ariaLabel": "Ouvrir le dépôt GitHub HagiCode"
      },
      "discord": {
        "label": "Discord",
        "ariaLabel": "Ouvrir la communauté Discord HagiCode"
      },
      "qqGroup": {
        "label": "QQ Group 610394020",
        "ariaLabel": "Ouvrir le groupe QQ HagiCode 610394020"
      },
      "email": {
        "label": "support@hagicode.com",
        "ariaLabel": "Envoyer un e-mail à l’équipe support HagiCode"
      },
      "steam": {
        "label": "Steam",
        "ariaLabel": "Ouvrir la page Steam officielle de HagiCode"
      },
      "filings": {
        "icpAriaLabel": "Voir l’enregistrement ICP",
        "publicSecurityAriaLabel": "Voir l’enregistrement de sécurité publique"
      }
    }
  },
  "home": {
    "workbenchAriaLabel": "Atelier Soul Builder",
    "hero": {
      "eyebrow": "Soul Builder",
      "title": "Compose le cadre de persona avant que la sortie ne commence à dériver.",
      "description": "Choisis un rôle de base, verrouille une règle d’expression, puis affine le prompt en direct dans un même atelier monochrome.",
      "primaryAction": "Aller à l’éditeur",
      "secondaryAction": "Ouvrir la documentation",
      "stats": {
        "catalog": "Rôles de base",
        "expression": "Règles d’expression",
        "state": "Atelier"
      },
      "state": {
        "ready": "Prêt à copier",
        "draft": "Composition incomplète"
      }
    },
    "slotRail": {
      "leftAriaLabel": "Emplacements de gauche",
      "rightAriaLabel": "Emplacements de droite",
      "inputsEyebrow": "entrées du builder",
      "contextEyebrow": "contexte du builder",
      "recommended": "recommandé"
    },
    "slots": {
      "catalog": {
        "label": "Rôle de base",
        "title": "Choisir un rôle de base",
        "description": "Verrouille d’abord le rôle de base pour définir le cadre de la persona et ses limites principales.",
        "emptyState": "Aucun rôle de base n’est disponible pour le moment."
      },
      "expression": {
        "label": "Expression",
        "title": "Choisir un style d’expression",
        "description": "Ajoute ensuite des règles d’expression pour resserrer le rythme, le ton et la cadence de sortie.",
        "emptyState": "Aucune règle d’expression n’est disponible pour le moment."
      }
    },
    "drawer": {
      "inputBadge": "Tiroir d’entrée",
      "contextBadge": "Tiroir de contexte",
      "defaultTitle": "Tiroir de contexte",
      "defaultDescription": "Aucun guidage n’est encore disponible pour cet emplacement.",
      "defaultEmptyState": "Aucun contenu n’est encore disponible pour cet emplacement.",
      "closeLabel": "Fermer le tiroir"
    }
  },
  "builder": {
    "categories": {
      "all": "Tout",
      "healingCompanion": "Guérison et compagnie",
      "characterPersona": "Personas de personnage",
      "professionalIdentity": "Identités professionnelles",
      "communityCulture": "Cultures communautaires",
      "contrastAndScene": "Contraste et scènes dédiées"
    },
    "materialLibrary": {
      "searchAriaLabel": "Rechercher des matériaux",
      "mainCategoryLabel": "Catégories de rôles de base",
      "refreshInspiration": "Actualiser l’inspiration",
      "selectedBadge": "Sélectionné",
      "importedBadge": "Importé",
      "importableBadge": "Importable",
      "styleFallback": "Exemple",
      "clickToImport": "Cliquer pour importer",
      "emptyFiltered": "Aucun matériau ne correspond aux filtres actuels.",
      "emptyInspiration": "Les cartes d’inspiration officielles sont indisponibles pour le moment. Tu peux tout de même composer avec les rôles de base et règles d’expression locales.",
      "panels": {
        "main": {
          "badge": "Rôle de base",
          "title": "Choisis d’abord un rôle de base.",
          "placeholder": "Rechercher des rôles de base"
        },
        "rules": {
          "badge": "Expression",
          "title": "Verrouille ensuite le style d’expression.",
          "placeholder": "Rechercher des règles d’expression"
        },
        "inspiration": {
          "badge": "Inspiration",
          "title": "Importer une carte d’inspiration officielle.",
          "placeholder": "Rechercher des cartes d’inspiration"
        },
        "all": {
          "badge": "Bibliothèque de matériaux",
          "title": "Commence par des fragments réutilisables.",
          "placeholder": "Rechercher rôles de base, règles ou cartes d’inspiration"
        }
      },
      "sections": {
        "mainTitle": "Rôles de base",
        "mainEyebrow": "who",
        "rulesTitle": "Règles d’expression",
        "rulesEyebrow": "how",
        "inspirationTitle": "Cartes d’inspiration officielles",
        "inspirationEyebrow": "inspiration",
        "remoteSourceTitle": "Source officielle d’inspiration"
      },
      "remote": {
        "loadingInitial": "Chargement des cartes d’inspiration officielles.",
        "loadingRefresh": "Actualisation des cartes d’inspiration officielles.",
        "fallback": "La source officielle d’inspiration est hors ligne, des cartes d’exemple locales sont donc affichées.",
        "empty": "La source officielle d’inspiration est vide, l’affichage est donc revenu aux cartes d’exemple locales.",
        "ready": "Les cartes d’inspiration officielles sont disponibles.",
        "errorWithFallback": "{{detail}} Retour aux cartes d’exemple locales.",
        "state": {
          "idle": "Inactif",
          "loading": "Chargement",
          "ready": "En ligne",
          "fallback": "Repli",
          "error": "Erreur"
        }
      }
    },
    "preview": {
      "panelTitle": "Éditeur Agent Soul",
      "defaultTitle": "Aperçu Soul Builder",
      "untitledSoul": "Soul sans titre",
      "feedbackSummary": "{{filled}} des 3 emplacements sont remplis. L’aperçu est recalculé en direct dans l’ordre.",
      "fallbackPartial": "Termine les emplacements restants et l’aperçu complet se mettra ici à jour automatiquement.",
      "fallbackInitial": "Remplis d’abord les emplacements du rôle de base et de l’expression avant que l’aperçu puisse former un résultat complet.",
      "nextReady": "Les trois emplacements sont fusionnés. Continue à peaufiner le texte ou copie immédiatement l’aperçu actuel.",
      "nextIncomplete": "Complète les emplacements manquants avant que l’aperçu ne se stabilise.",
      "previewEyebrow": "aperçu",
      "previewReady": "Fusionné et prêt à copier",
      "previewIncomplete": "Des emplacements requis manquent",
      "copyButton": "Copier l’aperçu",
      "currentCompositionTitle": "Composition actuelle",
      "nextStepTitle": "Étape suivante",
      "currentCompositionMain": "Rôle de base : {{value}}",
      "currentCompositionRule": "Expression : {{value}}",
      "currentCompositionCustom": "Texte personnalisé : {{value}}",
      "slots": {
        "main": {
          "eyebrow": "slot 01 · base role",
          "title": "Emplacement du rôle de base",
          "placeholder": "Choisis une carte de rôle de base à gauche, puis continue à l’éditer si besoin.",
          "ariaLabel": "Emplacement du rôle de base",
          "emptySummary": "Rôle de base non rempli"
        },
        "rule": {
          "eyebrow": "slot 02 · expression",
          "title": "Emplacement de l’expression",
          "placeholder": "Choisis une carte d’expression à gauche, puis continue à l’éditer si besoin.",
          "ariaLabel": "Emplacement de l’expression",
          "emptySummary": "Expression non remplie"
        },
        "custom": {
          "eyebrow": "slot 03 · custom",
          "title": "Emplacement du texte personnalisé",
          "placeholder": "Ajoute tes propres limites, préférences, tics de langage ou exigences supplémentaires.",
          "ariaLabel": "Emplacement du texte personnalisé",
          "filledSummary": "{{count}} caractères ajoutés",
          "emptySummary": "Aucune exigence supplémentaire pour l’instant"
        }
      },
      "hints": {
        "missingBoth": "Remplis d’abord les emplacements du rôle de base et de l’expression avant de générer un résultat complet.",
        "missingMain": "Remplis d’abord l’emplacement du rôle de base.",
        "missingRule": "Remplis d’abord l’emplacement de l’expression.",
        "copyIncompleteFallback": "La composition principale n’est pas encore prête.",
        "copySuccess": "Le texte d’aperçu a été copié.",
        "inspirationImported": "La carte d’inspiration \"{{title}}\" a été importée."
      }
    }
  }
} as const
