/* This file is generated by scripts/generate-i18n-resources.mjs. Do not edit by hand. */

export const ruRUResources = {
  "common": {
    "languages": {
      "zhCN": "中文",
      "enUS": "EN"
    },
    "states": {
      "selected": "Выбрано",
      "imported": "Импортировано",
      "importable": "Можно импортировать",
      "sample": "Пример",
      "loading": "Загрузка",
      "ready": "Доступно",
      "fallback": "Локальный резерв",
      "error": "Ошибка"
    }
  },
  "site": {
    "header": {
      "ariaLabel": "Заголовок сайта Soul",
      "navAriaLabel": "Навигация сайта Soul",
      "brandBadge": "Редактор Agent Soul",
      "description": "HagiSoul даёт разработчикам более быстрый интерфейс для создания, публикации и просмотра Souls.",
      "themeButton": "Тема",
      "themeToDark": "Переключить на тёмную тему",
      "themeToLight": "Переключить на светлую тему",
      "languageSwitcherAria": "Переключение языка интерфейса"
    },
    "footer": {
      "ariaLabel": "Подвал HagiSoul",
      "brandSectionAria": "Обзор бренда",
      "tagline": "Быстро задай душу своему Agent.",
      "description": "HagiSoul сосредоточен на рабочих процессах разработчиков и даёт более быстрый способ создавать, публиковать и просматривать Souls.",
      "copyright": "© {{year}} HagiCode. Все права защищены.",
      "sections": {
        "related": "Связанные ссылки",
        "community": "Сообщество и поддержка"
      }
    },
    "links": {
      "docs": {
        "label": "Docs",
        "ariaLabel": "Открыть сайт документации HagiCode"
      },
      "website": {
        "label": "Сайт",
        "ariaLabel": "Открыть сайт HagiCode"
      },
      "trait": {
        "label": "Trait",
        "ariaLabel": "Открыть конструктор HagiTrait"
      },
      "github": {
        "label": "GitHub",
        "ariaLabel": "Открыть репозиторий HagiCode на GitHub"
      },
      "discord": {
        "label": "Discord",
        "ariaLabel": "Открыть Discord-сообщество HagiCode"
      },
      "qqGroup": {
        "label": "QQ Group 610394020",
        "ariaLabel": "Открыть QQ-группу HagiCode 610394020"
      },
      "email": {
        "label": "support@hagicode.com",
        "ariaLabel": "Написать команде поддержки HagiCode"
      },
      "steam": {
        "label": "Steam",
        "ariaLabel": "Открыть официальную страницу HagiCode в Steam"
      },
      "filings": {
        "icpAriaLabel": "Показать запись ICP",
        "publicSecurityAriaLabel": "Показать запись общественной безопасности"
      }
    }
  },
  "home": {
    "workbenchAriaLabel": "Рабочее пространство Soul Builder",
    "hero": {
      "eyebrow": "Soul Builder",
      "title": "Сначала собери каркас персонажа, пока вывод ещё не начал расползаться.",
      "description": "Выбери базовую роль, зафиксируй правило выражения и отполируй живой промпт в одном монохромном рабочем пространстве.",
      "primaryAction": "Перейти к редактору",
      "secondaryAction": "Открыть документацию",
      "stats": {
        "catalog": "Базовые роли",
        "expression": "Правила выражения",
        "state": "Рабочее пространство"
      },
      "state": {
        "ready": "Готово к копированию",
        "draft": "Ещё нужно собрать"
      }
    },
    "slotRail": {
      "leftAriaLabel": "Левые слоты домашней страницы",
      "rightAriaLabel": "Правые слоты домашней страницы",
      "inputsEyebrow": "входы builder",
      "contextEyebrow": "контекст builder",
      "recommended": "рекомендовано"
    },
    "slots": {
      "catalog": {
        "label": "Базовая роль",
        "title": "Выбрать базовую роль",
        "description": "Сначала зафиксируй базовую роль, чтобы определить каркас персонажа и основные границы.",
        "emptyState": "Сейчас нет доступных базовых ролей."
      },
      "expression": {
        "label": "Выражение",
        "title": "Выбрать стиль выражения",
        "description": "Затем добавь правила выражения, чтобы подтянуть ритм, тон и манеру вывода.",
        "emptyState": "Сейчас нет доступных правил выражения."
      }
    },
    "drawer": {
      "inputBadge": "Входной ящик",
      "contextBadge": "Контекстный ящик",
      "defaultTitle": "Контекстный ящик",
      "defaultDescription": "Для этого слота пока нет подсказок.",
      "defaultEmptyState": "Для этого слота пока нет содержимого.",
      "closeLabel": "Закрыть ящик"
    }
  },
  "builder": {
    "categories": {
      "all": "Все",
      "healingCompanion": "Исцеление и сопровождение",
      "characterPersona": "Персоны персонажей",
      "professionalIdentity": "Профессиональные идентичности",
      "communityCulture": "Культуры сообществ",
      "contrastAndScene": "Контраст и сценические роли"
    },
    "materialLibrary": {
      "searchAriaLabel": "Искать материалы",
      "mainCategoryLabel": "Категории базовых ролей",
      "refreshInspiration": "Обновить вдохновение",
      "selectedBadge": "Выбрано",
      "importedBadge": "Импортировано",
      "importableBadge": "Можно импортировать",
      "styleFallback": "Пример",
      "clickToImport": "Нажмите для импорта",
      "emptyFiltered": "Ни один материал не соответствует текущим фильтрам.",
      "emptyInspiration": "Официальные карточки вдохновения сейчас недоступны. Ты всё равно можешь собирать результат на локальных базовых ролях и правилах выражения.",
      "panels": {
        "main": {
          "badge": "Базовая роль",
          "title": "Сначала выбери базовую роль.",
          "placeholder": "Искать базовые роли"
        },
        "rules": {
          "badge": "Выражение",
          "title": "Затем зафиксируй стиль выражения.",
          "placeholder": "Искать правила выражения"
        },
        "inspiration": {
          "badge": "Вдохновение",
          "title": "Импортировать официальную карточку вдохновения.",
          "placeholder": "Искать карточки вдохновения"
        },
        "all": {
          "badge": "Библиотека материалов",
          "title": "Начни с переиспользуемых фрагментов.",
          "placeholder": "Искать базовые роли, правила или карточки вдохновения"
        }
      },
      "sections": {
        "mainTitle": "Базовые роли",
        "mainEyebrow": "who",
        "rulesTitle": "Правила выражения",
        "rulesEyebrow": "how",
        "inspirationTitle": "Официальные карточки вдохновения",
        "inspirationEyebrow": "inspiration",
        "remoteSourceTitle": "Официальный источник вдохновения"
      },
      "remote": {
        "loadingInitial": "Загружаются официальные карточки вдохновения.",
        "loadingRefresh": "Обновляются официальные карточки вдохновения.",
        "fallback": "Официальный источник вдохновения недоступен, поэтому показываются локальные примерные карточки.",
        "empty": "Официальный источник вдохновения пуст, поэтому отображение вернулось к локальным примерным карточкам.",
        "ready": "Официальные карточки вдохновения доступны.",
        "errorWithFallback": "{{detail}} Выполнен возврат к локальным примерным карточкам.",
        "state": {
          "idle": "Ожидание",
          "loading": "Загрузка",
          "ready": "Доступно",
          "fallback": "Резерв",
          "error": "Ошибка"
        }
      }
    },
    "preview": {
      "panelTitle": "Редактор Agent Soul",
      "defaultTitle": "Предпросмотр Soul Builder",
      "untitledSoul": "Soul без названия",
      "feedbackSummary": "{{filled}} из 3 слотов заполнены. Предпросмотр пересчитывается вживую по порядку.",
      "fallbackPartial": "Заполни оставшиеся слоты, и полный предпросмотр автоматически обновится здесь.",
      "fallbackInitial": "Сначала заполни слоты базовой роли и выражения, прежде чем предпросмотр сможет сформировать полный результат.",
      "nextReady": "Все три слота объединены. Продолжай шлифовать текст или сразу копируй текущий предпросмотр.",
      "nextIncomplete": "Заполни недостающие слоты, прежде чем предпросмотр сможет стабилизироваться.",
      "previewEyebrow": "предпросмотр",
      "previewReady": "Объединено и готово к копированию",
      "previewIncomplete": "Не хватает обязательных слотов",
      "copyButton": "Скопировать предпросмотр",
      "currentCompositionTitle": "Текущая композиция",
      "nextStepTitle": "Следующий шаг",
      "currentCompositionMain": "Базовая роль: {{value}}",
      "currentCompositionRule": "Выражение: {{value}}",
      "currentCompositionCustom": "Пользовательский текст: {{value}}",
      "slots": {
        "main": {
          "eyebrow": "slot 01 · base role",
          "title": "Слот базовой роли",
          "placeholder": "Выбери карточку базовой роли слева, затем при необходимости продолжай редактировать.",
          "ariaLabel": "Слот базовой роли",
          "emptySummary": "Базовая роль не заполнена"
        },
        "rule": {
          "eyebrow": "slot 02 · expression",
          "title": "Слот выражения",
          "placeholder": "Выбери карточку выражения слева, затем при необходимости продолжай редактировать.",
          "ariaLabel": "Слот выражения",
          "emptySummary": "Выражение не заполнено"
        },
        "custom": {
          "eyebrow": "slot 03 · custom",
          "title": "Слот пользовательского текста",
          "placeholder": "Добавь собственные ограничения, предпочтения, словечки или дополнительные требования.",
          "ariaLabel": "Слот пользовательского текста",
          "filledSummary": "Добавлено {{count}} символов",
          "emptySummary": "Дополнительных требований пока нет"
        }
      },
      "hints": {
        "missingBoth": "Сначала заполни слоты базовой роли и выражения, прежде чем генерировать полный результат.",
        "missingMain": "Сначала заполни слот базовой роли.",
        "missingRule": "Сначала заполни слот выражения.",
        "copyIncompleteFallback": "Основная композиция ещё не готова.",
        "copySuccess": "Текст предпросмотра скопирован.",
        "inspirationImported": "Карточка вдохновения \"{{title}}\" импортирована."
      }
    }
  }
} as const
