/* This file is generated by scripts/generate-i18n-resources.mjs. Do not edit by hand. */

export const zhHantResources = {
  "common": {
    "languages": {
      "zhCN": "中文",
      "enUS": "EN"
    },
    "states": {
      "selected": "已選取",
      "imported": "已匯入",
      "importable": "可匯入",
      "sample": "範例",
      "loading": "載入中",
      "ready": "已上線",
      "fallback": "本地回退",
      "error": "錯誤"
    }
  },
  "site": {
    "header": {
      "ariaLabel": "Soul 站點頁首",
      "navAriaLabel": "Soul 站點導覽",
      "brandBadge": "Agent Soul 編輯器",
      "description": "HagiSoul 為開發者提供更流暢的 Soul 編輯空間，支援 Soul 的建立、分享與瀏覽。",
      "themeButton": "主題",
      "themeToDark": "切換為深色主題",
      "themeToLight": "切換為淺色主題",
      "languageSwitcherAria": "介面語言切換"
    },
    "footer": {
      "ariaLabel": "HagiSoul 頁尾",
      "brandSectionAria": "品牌資訊",
      "tagline": "快速定義你的 Agent 之魂。",
      "description": "HagiSoul 聚焦開發者工作流程，提供更順手的 Soul 建立、分享與瀏覽體驗。",
      "copyright": "© {{year}} HagiCode。保留所有權利。",
      "sections": {
        "related": "相關連結",
        "community": "社群與支援"
      }
    },
    "links": {
      "docs": {
        "label": "文件",
        "ariaLabel": "開啟 HagiCode 官方文件"
      },
      "website": {
        "label": "官網",
        "ariaLabel": "開啟 HagiCode 官網"
      },
      "trait": {
        "label": "Trait",
        "ariaLabel": "開啟 HagiTrait 建構器"
      },
      "github": {
        "label": "GitHub",
        "ariaLabel": "開啟 HagiCode GitHub 倉庫"
      },
      "discord": {
        "label": "Discord",
        "ariaLabel": "開啟 HagiCode Discord 社群"
      },
      "qqGroup": {
        "label": "QQ 群 610394020",
        "ariaLabel": "開啟 HagiCode QQ 群 610394020"
      },
      "email": {
        "label": "support@hagicode.com",
        "ariaLabel": "透過電子郵件聯絡 HagiCode 支援團隊"
      },
      "steam": {
        "label": "Steam",
        "ariaLabel": "開啟 HagiCode 官方 Steam 商店頁"
      },
      "filings": {
        "icpAriaLabel": "查看 ICP 備案資訊",
        "publicSecurityAriaLabel": "查看公安備案資訊"
      }
    }
  },
  "home": {
    "workbenchAriaLabel": "Soul Builder 工作台",
    "hero": {
      "eyebrow": "Soul Builder",
      "title": "先定人格骨架，再讓輸出不走樣。",
      "description": "先挑基礎角色，再鎖定表達規則，最後在同一塊黑白工作台中打磨即時提示詞。",
      "primaryAction": "進入編輯器",
      "secondaryAction": "開啟文件",
      "stats": {
        "catalog": "基礎角色",
        "expression": "表達規則",
        "state": "工作台"
      },
      "state": {
        "ready": "可直接複製",
        "draft": "仍待組合"
      }
    },
    "slotRail": {
      "leftAriaLabel": "左側首頁槽位",
      "rightAriaLabel": "右側首頁槽位",
      "inputsEyebrow": "編輯器輸入",
      "contextEyebrow": "編輯器上下文",
      "recommended": "推薦"
    },
    "slots": {
      "catalog": {
        "label": "基礎角色",
        "title": "選擇基礎角色",
        "description": "先鎖定基礎角色，確定人格骨架與核心邊界。",
        "emptyState": "目前沒有可用的基礎角色。"
      },
      "expression": {
        "label": "表達方式",
        "title": "選擇表達方式",
        "description": "再加入表達規則，收緊節奏、語氣與輸出節律。",
        "emptyState": "目前沒有可用的表達規則。"
      }
    },
    "drawer": {
      "inputBadge": "輸入抽屜",
      "contextBadge": "上下文抽屜",
      "defaultTitle": "上下文抽屜",
      "defaultDescription": "這個槽位目前沒有說明。",
      "defaultEmptyState": "這個槽位目前沒有內容。",
      "closeLabel": "關閉抽屜"
    }
  },
  "builder": {
    "categories": {
      "all": "全部",
      "healingCompanion": "治癒陪伴向",
      "characterPersona": "個性人設向",
      "professionalIdentity": "職業身份向",
      "communityCulture": "圈層文化向",
      "contrastAndScene": "反差與場景專屬向"
    },
    "materialLibrary": {
      "searchAriaLabel": "搜尋素材",
      "mainCategoryLabel": "基礎角色分類",
      "refreshInspiration": "重新整理靈感",
      "selectedBadge": "已選取",
      "importedBadge": "已匯入",
      "importableBadge": "可匯入",
      "styleFallback": "範例",
      "clickToImport": "點擊匯入",
      "emptyFiltered": "目前篩選條件下沒有素材。",
      "emptyInspiration": "官方靈感卡暫時不可用。你仍可使用本地基礎角色與表達規則完成組合。",
      "panels": {
        "main": {
          "badge": "基礎角色",
          "title": "先挑選基礎角色。",
          "placeholder": "搜尋基礎角色"
        },
        "rules": {
          "badge": "表達方式",
          "title": "再鎖定表達方式。",
          "placeholder": "搜尋表達規則"
        },
        "inspiration": {
          "badge": "靈感",
          "title": "匯入官方靈感卡。",
          "placeholder": "搜尋靈感卡"
        },
        "all": {
          "badge": "素材庫",
          "title": "從可重用的片段開始。",
          "placeholder": "搜尋基礎角色、規則或靈感卡"
        }
      },
      "sections": {
        "mainTitle": "基礎角色",
        "mainEyebrow": "who",
        "rulesTitle": "表達規則",
        "rulesEyebrow": "how",
        "inspirationTitle": "官方靈感卡",
        "inspirationEyebrow": "inspiration",
        "remoteSourceTitle": "官方靈感來源"
      },
      "remote": {
        "loadingInitial": "正在載入官方靈感卡。",
        "loadingRefresh": "正在重新整理官方靈感卡。",
        "fallback": "官方靈感來源離線，已改顯示本地範例卡。",
        "empty": "官方靈感來源目前沒有內容，已切回本地範例卡。",
        "ready": "官方靈感卡已可用。",
        "errorWithFallback": "{{detail}} 已切回本地範例卡。",
        "state": {
          "idle": "待命",
          "loading": "載入中",
          "ready": "已上線",
          "fallback": "回退",
          "error": "錯誤"
        }
      }
    },
    "preview": {
      "panelTitle": "Agent Soul 編輯器",
      "defaultTitle": "Soul Builder 預覽",
      "untitledSoul": "未命名 Soul",
      "feedbackSummary": "3 個槽位中已填入 {{filled}} 個，預覽會依順序即時重算。",
      "fallbackPartial": "補完剩餘槽位後，這裡會自動刷新完整預覽。",
      "fallbackInitial": "先填入基礎角色與表達方式槽位，預覽才能形成完整結果。",
      "nextReady": "三個槽位已合併完成。繼續微調文字，或直接複製目前預覽。",
      "nextIncomplete": "先補齊缺失槽位，預覽才會穩定。",
      "previewEyebrow": "預覽",
      "previewReady": "已合併，可直接複製",
      "previewIncomplete": "缺少必要槽位",
      "copyButton": "複製預覽",
      "currentCompositionTitle": "目前組合",
      "nextStepTitle": "下一步建議",
      "currentCompositionMain": "基礎角色：{{value}}",
      "currentCompositionRule": "表達方式：{{value}}",
      "currentCompositionCustom": "自訂文字：{{value}}",
      "slots": {
        "main": {
          "eyebrow": "槽位 01 · 基礎角色",
          "title": "基礎角色槽位",
          "placeholder": "先在左側選擇一張基礎角色卡，再依需要繼續編輯。",
          "ariaLabel": "基礎角色槽位",
          "emptySummary": "基礎角色未填寫"
        },
        "rule": {
          "eyebrow": "槽位 02 · 表達方式",
          "title": "表達方式槽位",
          "placeholder": "先在左側選擇一張表達規則卡，再依需要繼續編輯。",
          "ariaLabel": "表達方式槽位",
          "emptySummary": "表達方式未填寫"
        },
        "custom": {
          "eyebrow": "槽位 03 · 自訂",
          "title": "自訂文字槽位",
          "placeholder": "補充你自己的限制、偏好、口頭禪或額外要求。",
          "ariaLabel": "自訂文字槽位",
          "filledSummary": "已新增 {{count}} 個字元",
          "emptySummary": "尚無額外要求"
        }
      },
      "hints": {
        "missingBoth": "先補基礎角色與表達方式槽位，才能生成完整結果。",
        "missingMain": "先補基礎角色槽位。",
        "missingRule": "先補表達方式槽位。",
        "copyIncompleteFallback": "核心組合尚未就緒。",
        "copySuccess": "預覽文字已複製。",
        "inspirationImported": "已匯入靈感卡「{{title}}」。"
      }
    }
  }
} as const
